/* eslint no-use-before-define: 0 */
import Head from 'next/head'
import Image from 'next/image'
import { useEffect } from 'react';

import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import * as d3 from 'd3';
import imageUrls from '@/image_urls.json';
import fs from "fs";


export default function Home(props) {
  const { imgUrls } = props

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.App}>
          <div id="my-svg" className={styles.mySVG}>
            { /* eslint-disable */
              // imgList.map(data => ( // eslint-disable-line no-use-before-define
              imgUrls && imgUrls.map(url => (
                // <Image src={`data:image/png;base64,${data}`} height={100} width={100} priority /> // eslint-disable-next-line no-use-before-define
                <Image src={url} height={100} width={100} priority /> // eslint-disable-next-line no-use-before-define
              ))}
          </div>
        </div>
      </main>
    </>
  )
}

export async function getStaticProps(context) {
  return {
    props: {
      imgUrls: imageUrls
      // imgList: imgBufs
    },
  }
}